{% set name = "lume-impact" %}
{% set version = "0.10.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 70bab178380565591d5e0f5de210b2633741ef2e8c0f90a716792c749df92d8f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - bokeh
    - distgen
    - impact-t >=3
    - impact-z >=2.7.2
    - lume-base
    - matplotlib-base
    - numpy
    - openpmd-beamphysics
    - polars
    - prettytable
    - psutil
    - pydantic
    - pydantic-settings
    - rich
    - tqdm
    - typing-extensions

test:
  imports:
    - impact
    - impact.z
  requires:
    - pytest
    - pytest-cov
    - bmad
    - pytao
    - python {{ python_min }}
  commands:
    - python -m pytest --pyargs impact -k "not test_bmad and not test_output"

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
    - ken-lauer
