{% set name = "lume-impact" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 0d8be8424dcdc21418bd3bda427a544f0fbaf2269dcee5561f86cb716cf82275

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - bokeh
    - distgen
    - numpy
    - openpmd-beamphysics
    - psutil
    - impact-t >=2,<3
    - lume-base

test:
  imports:
    - impact
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs impact

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: |
    LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
