{% set name = "lume-impact" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d185e3345c01bbdd70b68c2f5746af1bfc20ede2c7ec1655ffb5530f844e61c8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bokeh
    - distgen
    - numpy
    - openpmd-beamphysics
    - impact-t
    - lume-base

test:
  imports:
    - impact
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs impact

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: |
    LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
